name: SSH on Linux

on:
  workflow_dispatch:

jobs:
  ssh-access:
    runs-on: ubuntu-latest
    timeout-minutes: 3600

    steps:
      - name: SSH সার্ভার সেটআপ করুন
        run: |
          # SSH সার্ভার ইনস্টল এবং চালু করুন
          sudo apt-get update
          sudo apt-get install -y openssh-server
          sudo systemctl start ssh

      - name: ব্যবহারকারী তৈরি করুন
        run: |
          # একটি সহজ ৮-সংখ্যার র‍্যান্ডম পাসওয়ার্ড তৈরি করুন
          PASSWORD=$(tr -dc '0-9' < /dev/urandom | head -c 8)
          
          # 'sshuser' নামে নতুন ব্যবহারকারী তৈরি করুন এবং sudo ক্ষমতা দিন
          sudo useradd -m -s /bin/bash sshuser
          echo "sshuser:$PASSWORD" | sudo chpasswd
          sudo usermod -aG sudo sshuser
          
          # লগইন তথ্য GitHub পরিবেশে সংরক্ষণ করুন
          echo "SSH_CREDS=User: sshuser | Password: $PASSWORD" >> $GITHUB_ENV
          
      - name: Tailscale ইনস্টল করুন
        run: |
          # Tailscale-এর ইনস্টলেশন স্ক্রিপ্ট চালান
          curl -fsSL https://tailscale.com/install.sh | sh

      - name: Tailscale কানেকশন স্থাপন করুন
        run: |
          # আপনার দেওয়া auth key ব্যবহার করে Tailscale চালু করুন
          sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=gh-runner-linux-$GITHUB_RUN_ID
          
          # Tailscale IP পেতে অপেক্ষা করুন
          TS_IP=$(tailscale ip -4)
          while [ -z "$TS_IP" ]; do
              sleep 5
              TS_IP=$(tailscale ip -4)
          done
          echo "TAILSCALE_IP=$TS_IP" >> $GITHUB_ENV

      - name: কানেকশন চালু রাখুন এবং তথ্য দেখান
        run: |
          echo -e "\n=== SSH ACCESS (Linux) ==="
          echo "Address: $TAILSCALE_IP"
          echo "Command: ssh sshuser@$TAILSCALE_IP"
          echo "Credentials: $(echo $SSH_CREDS)"
          echo -e "=========================\n"
          
          # workflow চালু রাখার জন্য লুপ
          while true; do
              echo "[$(date)] SSH Active - workflow বন্ধ করতে Cancel বাটনে ক্লিক করুন"
              sleep 300
          done
