name: VNC on macOS

on:
  workflow_dispatch:

jobs:
  vnc-access:
    runs-on: macos-latest
    timeout-minutes: 3600

    steps:
      - name: ব্যবহারকারী তৈরি এবং VNC চালু করুন
        run: |
          # একটি শক্তিশালী র‍্যান্ডম পাসওয়ার্ড তৈরি করুন
          PASSWORD=$(openssl rand -base64 16)
          
          # 'vncuser' নামে নতুন ব্যবহারকারী তৈরি করুন এবং অ্যাডমিন ক্ষমতা দিন
          sudo dscl . -create /Users/vncuser
          sudo dscl . -create /Users/vncuser UserShell /bin/bash
          sudo dscl . -create /Users/vncuser RealName "VNC User"
          sudo dscl . -create /Users/vncuser UniqueID "1001"
          sudo dscl . -create /Users/vncuser PrimaryGroupID "20"
          sudo dscl . -create /Users/vncuser NFSHomeDirectory /Users/vncuser
          sudo dscl . -passwd /Users/vncuser "$PASSWORD"
          sudo dscl . -append /Groups/admin GroupMembership vncuser
          
          # Screen Sharing (VNC) চালু করুন
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -activate -configure -access -on -users vncuser -privs -all -restart -agent -menu
          
          # লগইন তথ্য GitHub পরিবেশে সংরক্ষণ করুন
          echo "VNC_CREDS=User: vncuser | Password: $PASSWORD" >> $GITHUB_ENV

      - name: Tailscale ইনস্টল করুন
        run: |
          # macOS-এর জন্য Tailscale ইনস্টলার ডাউনলোড এবং ইনস্টল করুন
          curl -fsSL https://pkgs.tailscale.com/stable/tailscale-latest.pkg -o tailscale.pkg
          sudo installer -pkg tailscale.pkg -target /

      - name: Tailscale কানেকশন স্থাপন করুন
        run: |
          # আপনার দেওয়া auth key ব্যবহার করে Tailscale চালু করুন
          sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=gh-runner-macos-$GITHUB_RUN_ID
          
          # Tailscale IP পেতে অপেক্ষা করুন
          TS_IP=$(tailscale ip -4)
          while [ -z "$TS_IP" ]; do
              sleep 5
              TS_IP=$(tailscale ip -4)
          done
          echo "TAILSCALE_IP=$TS_IP" >> $GITHUB_ENV

      - name: কানেকশন চালু রাখুন এবং তথ্য দেখান
        run: |
          echo -e "\n=== VNC ACCESS (macOS) ==="
          echo "Address: $TAILSCALE_IP"
          echo "VNC Address: vnc://$TAILSCALE_IP"
          echo "Credentials: $(echo $VNC_CREDS)"
          echo -e "=========================\n"
          
          # workflow চালু রাখার জন্য লুপ
          while true; do
              echo "[$(date)] VNC Active - workflow বন্ধ করতে Cancel বাটনে ক্লিক করুন"
              sleep 300
          done
